# Generated by Django 5.0 on 2023-12-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionTest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('lt_sph', models.IntegerField()),
                ('lt_cyl', models.IntegerField()),
                ('lt_axis', models.IntegerField()),
                ('rt_sph', models.IntegerField()),
                ('rt_cyl', models.IntegerField()),
                ('rt_axis', models.IntegerField()),
            ],
        ),
    ]
