# Generated by Django 5.0 on 2023-12-22 01:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointmentId', models.IntegerField()),
                ('patientId', models.IntegerField()),
                ('status', models.CharField(choices=[('PN', 'Pending Payment'), ('PD', 'Paid')], default='PN', max_length=2)),
                ('dateTime', models.DateTimeField()),
                ('servicesIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('ON', 'Card'), ('OF', 'Offline')], default='OF', max_length=2)),
                ('dateTime', models.DateTimeField()),
                ('invoiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_app.invoice')),
            ],
        ),
    ]
