# Generated by Django 5.0 on 2023-12-09 19:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.IntegerField(null=True)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='OF', max_length=2)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insurance_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PN', 'Pending Payment'), ('PD', 'Paid'), ('CN', 'Cancelled')], default='DR', max_length=2)),
                ('datetime', models.DateTimeField()),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
