# Generated by Django 4.2.7 on 2023-12-20 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="datetime",
            new_name="dateTime",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="invoice_id",
            new_name="invoiceId",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="payment_method",
            new_name="paymentMethod",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="appointment_id",
            new_name="appointmentId",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="datetime",
            new_name="dateTime",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="id",
            new_name="invoiceId",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="services_ids",
            new_name="servicesIds",
        ),
    ]
