# Generated by Django 5.0 on 2023-12-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paymentMethod',
            field=models.CharField(choices=[('ON', 'Card'), ('OF', 'Offline')], default='OF', max_length=2),
        ),
    ]
