# Generated by Django 4.2.7 on 2023-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing_app", "0002_alter_bill_paymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="appointmentId",
            field=models.CharField(),
        ),
    ]
