# Generated by Django 4.2.7 on 2023-12-20 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing_app", "0002_rename_datetime_bill_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="invoiceId",
            new_name="id",
        ),
    ]
